server:
  port: 8080

spring:
  application:
    name: smsf-masterdata-service
  main:
    allow-bean-definition-overriding: true

smsf:
  data:
    mybatis:
      mapper-locations: classpath*:/mapper/*.xml
    jdbc:
      connections:
        default:
          url: jdbc:mysql://${smsf.data.database1.url}/smsf_master_data?useUnicode=true&useSSL=false&characterEncoding=utf-8
          username: ${smsf.data.database1.username}
          password: ${smsf.data.database1.password}
  cache:
    redis-cache:
      process:
        duration: 10
      step:
        duration: 10
      companyservicelevel:
        duration: 10
logging:
  level:
    com.accenture.masterdata.core.mapper: debug