server:
  port: 8080

spring:
  application:
    name: smsf-masterdata-service
  main:
    allow-bean-definition-overriding: true

smsf:
  data:
    mybatis:
      mapper-locations: classpath*:/mapper/*.xml
    jdbc:
      connections:
        default:
          url: jdbc:mysql://127.0.0.1:3306/smsf_master_data?useUnicode=true&useSSL=false&characterEncoding=utf-8
          username: root
          password: root
logging:
  level:
    com.accenture.masterdata.core.mapper: debug